### PR TITLE
GAWB-2578 - Land on catalog page

### PR DESCRIPTION
**Pull request by vvicario**

### CODE REVIEW

**Review by dags — APPROVED** [review]

**Review by davidangb — APPROVED** [review]
:+1: code looks good to me; did not test.

**Review by rushtong — APPROVED** [review]
👍  Code looks good, tested as a researcher and was successfully directed to the dataset catalog page.

**Comment by rushtong** [comment]
@vvicario, @dags - Going through open PRs and found this one. Please let me know if you need any further feedback - it's ready to merge from my perspective.

**Comment by dags** [comment]
Let me review it and i'll let you know. As far as I remember, it should be merged.Regards.Diego.El 20 nov. 2017 10:23, Greg Rushton <notifications@github.com> escribió:@vvicario, @dags - Going through open PRs and found this one. Please let me know if you need any further feedback - it's ready to merge from my perspective.

**Comment by rushtong** [comment]
Merging on behalf of Diego and Veronica.

**Pull request merged**
