### PR TITLE
GAWB-3171 DUOS download format bug

### PR DESCRIPTION
**Pull request by zarsky-broad**

### CODE REVIEW

**Comment by rushtong** [comment]
This looks great. However, when discussing this with you, I mis-read Moran's requirements. I believe the story requires that the structured (or textual) format be displayed on the page instead of being a download. The download link we need to have is the machine readable (`json`) version. Very sorry this got lost in translation yesterday.

**Review by rushtong — CHANGES_REQUESTED** [review]
See comment

**Comment by davidangb** [comment]
Sounds like this still has requirements questions. I am skipping review; if you can get two other thumbs, all good (and if it's still open next week I will review)

**Review by rushtong — APPROVED** [review]

**Comment by rushtong** [comment]
Still 👍

**Review by s-rubenstein — APPROVED** [review]
Reviewed over screenshare. Looks good to me.

**Pull request merged**
